package com.sthoray.allright.metaDataProduct

data class Manager(
    val active_offer: ActiveOffer,
    val aggregate_rating: Any,
    val award: Any,
    val `class`: Any,
    val config: Config,
    val contact_hours: Any,
    val cover_image: String,
    val created_at: String,
    val custom_url: Any,
    val department: Any,
    val description: String,
    val faqs: Any,
    val id: Int,
    val is_dropshipper: Int,
    val is_international: Int,
    val legal_name: Any,
    val location_name: String,
    val logo: Logo,
    val media_url: Any,
    val name: String,
    val pickups: Int,
    val policies: Any,
    val postcode: Any,
    val primary_manager_id: Int,
    val primary_phone: Any,
    val sells_used: Int,
    val ship_time_days: Int,
    val state: Int,
    val status: Int,
    val store_offer_id: Int,
    val stripe_id: String,
    val type: Int,
    val updated_at: String,
    val website: String
)