package com.sthoray.allright.metaDataSearch

data class CategoryX(
    val app_icon: String,
    val auction_count: Int,
    val auctionable: Int,
    val `class`: Int,
    val consumable_days: Any,
    val created_at: String,
    val custom_explanation: Int,
    val default_brand_new: Int,
    val default_fast_shipping: Int,
    val default_free_shipping: Int,
    val default_layout_list: Int,
    val display: Int,
    val icon: String,
    val id: Int,
    val identity_color: Any,
    val is_restricted: Int,
    val level: Int,
    val listing_count: Int,
    val name: String,
    val oversized: Int,
    val owner: Int,
    val parent: Parent,
    val product_count: Int,
    val productable: Int,
    val properties: List<PropertyX>,
    val quality: Int,
    val risk_level: Int,
    val show_good_as_new_in_secondhand: Int,
    val state: Int,
    val type: Any,
    val updated_at: String,
    val value: Int
)