name: Android Feature Branch CI

on:
  push:
    branches: [ '*' ,'!master' ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Unit tests
      run: bash ./gradlew test --stacktrace

  testui:
    # We can use HW acceleration when using a macOS VM
    name: Run Instrumented Tests
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew connectedAndroidTest -i
