name: Android CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  instrumented-tests:
    name: Instrumented Tests
    runs-on: macos-latest

    strategy:
      matrix:
        api-level: [ 21, 24, 26, 30 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Run instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          script: ./gradlew connectedAndroidTest

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK
        uses: actions/setup-java@v1.4.2
        with:
          java-version: 11

      - name: Build with Gradle
        run: ./gradlew build --stacktrace

  apk:
    name: Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK
        uses: actions/setup-java@v1.4.2
        with:
          java-version: 11

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

  codecov:
    name: Codecov
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Run instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          script: ./gradlew jacocoTestReport connectedAndroidTest

      - name: Upload coverage reports
        run: bash <(curl -s https://codecov.io/bash)
