name: Android Feature CI

on:
  push:
    branches: [ '*' ,'!master', '!gh-pages' ]

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Run unit tests
      run: ./gradlew test --stacktrace

  testui:
    name: Instrumented Tests
    runs-on: macos-latest # HW acceleration is available only on a macOS VM
    strategy:
      matrix:
        api-level: [ 24, 26, 30 ]
        target: [ default, google_apis ]
    steps:
    - uses: actions/checkout@v2

    - name: Run instrumented tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        script: ./gradlew connectedAndroidTest -i
