name: Code coverage

on:
  push:
    branches: master

jobs:
  codecov:
    name: Codecov
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Run instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          script: ./gradlew jacocoTestReport connectedAndroidTest

      - name: Upload coverage reports
        run: bash <(curl -s https://codecov.io/bash)
