name: Documentation

on:
  push:
    branches: master

jobs:
  dokka:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Merge changes
        run: |
          git config --local user.email "20161450+scsole@users.noreply.github.com"
          git config --local user.name "Sebastian Sole"
          git merge origin/master

      - name: Extract docs
        run: |
          rm -rf dokka
          ./gradlew dokka

      - name: Commit files
        run: |
          git add -f docs
          git diff-index --quiet HEAD || git commit -m "Automatically update docs"

      - name: Push changes
        run: git push
