name: Documentation

on:
  push:
    branches: master

jobs:
  dokka:
    name: Dokka
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK
        uses: actions/setup-java@v1.4.2
        with:
          java-version: 11

      - name: Merge changes
        run: |
          git config --local user.email "20161450+scsole@users.noreply.github.com"
          git config --local user.name "Sebastian Sole"
          git merge origin/master

      - name: Generate docs
        run: |
          rm -rf docs
          ./gradlew dokkaHtml
          mv app/build/dokka/html ./docs

      - name: Commit changes
        run: |
          git add -f docs
          git diff-index --quiet HEAD || git commit -m "Automatically update docs"

      - name: Push changes
        run: git push
