name: Documentation

on:
  push:
    branches: master

jobs:
  dokka:
    name: Dokka
    runs-on: ubuntu-latest
    steps:
      - uses: everlytic/branch-merge@1.0.2
        with:
          source_ref: master
          target_branch: gh-pages

      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Extract docs
        run: |
          rm -rf dokka
          ./gradlew dokka

      - name: Commit files
        run: |
          git config --local user.email "actionsbot@users.noreply.github.com"
          git config --local user.name "Actions Bot"
          git add -f dokka
          git diff-index --quiet HEAD || git commit -m "Updated docs"

      - name: Push changes
        run: git push
